import { TarotCard, SpreadDefinition } from "./types";

export const MAJOR_ARCANA: TarotCard[] = [
  {
    id: "major-00-the-fool",
    name: "The Fool",
    number: 0,
    romanNumeral: "0",
    arcana: "major",
    suit: null,
    element: "air",
    archetype: "The Leap of Faith & The Holy Innocent",
    keywords: {
      upright: ["Beginnings", "Innocence", "Spontaneity", "Free Spirit"],
      reversed: ["Recklessness", "Risk-taking", "Hesitation", "Naivety"],
    },
    summary: {
      upright: "A fresh journey begins. Step forward into the unknown with an open heart and quiet trust in life.",
      reversed: "Be mindful of rash impulses, or examine where self-doubt is holding you back from a necessary start.",
    },
  },
  {
    id: "major-01-the-magician",
    name: "The Magician",
    number: 1,
    romanNumeral: "I",
    arcana: "major",
    suit: null,
    element: "air",
    archetype: "Conscious Will & Manifestation",
    keywords: {
      upright: ["Willpower", "Desire", "Creation", "Resourcefulness"],
      reversed: ["Illusion", "Scattered Energy", "Wasted Talent", "Manipulation"],
    },
    summary: {
      upright: "As above, so below. You possess all the tools and internal clarity needed to bring your intention to life.",
      reversed: "Align your inner intentions with your actions. Guard against deceptive illusions or scattered focus.",
    },
  },
  {
    id: "major-02-the-high-priestess",
    name: "The High Priestess",
    number: 2,
    romanNumeral: "II",
    arcana: "major",
    suit: null,
    element: "water",
    archetype: "The Subconscious Mirror & Inner Knowing",
    keywords: {
      upright: ["Intuition", "Sacred Knowledge", "Divine Feminine", "Subconscious"],
      reversed: ["Secrets", "Disconnected Intuition", "Withdrawal", "Surface Level"],
    },
    summary: {
      upright: "Turn inward. The answer is not in the outer noise, but in the quiet stillness beneath your conscious thoughts.",
      reversed: "You may be ignoring your instincts or allowing external chatter to drown out your inner compass.",
    },
  },
  {
    id: "major-03-the-empress",
    name: "The Empress",
    number: 3,
    romanNumeral: "III",
    arcana: "major",
    suit: null,
    element: "earth",
    archetype: "Abundance, Nurturance & Creative Fertility",
    keywords: {
      upright: ["Fertility", "Sensuality", "Nurturing", "Abundance"],
      reversed: ["Creative Block", "Depletion", "Overbearing", "Neglect"],
    },
    summary: {
      upright: "A season of flourishing and gentle growth. Nourish your body, your environment, and your creative sparks.",
      reversed: "Replenish your inner reserves. You cannot pour from an empty cup; focus on somatic self-care.",
    },
  },
  {
    id: "major-04-the-emperor",
    name: "The Emperor",
    number: 4,
    romanNumeral: "IV",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Structure, Order & Grounded Authority",
    keywords: {
      upright: ["Stability", "Structure", "Protection", "Sovereignty"],
      reversed: ["Rigidity", "Control Issues", "Chaos", "Inflexibility"],
    },
    summary: {
      upright: "Create healthy boundaries and deliberate structure. Step into quiet self-mastery and ownership.",
      reversed: "Examine where stubborn rigidity is creating unnecessary friction. True strength bends with the wind.",
    },
  },
  {
    id: "major-05-the-hierophant",
    name: "The Hierophant",
    number: 5,
    romanNumeral: "V",
    arcana: "major",
    suit: null,
    element: "earth",
    archetype: "Tradition, Spiritual Lineage & Core Values",
    keywords: {
      upright: ["Wisdom", "Tradition", "Mentorship", "Belief Systems"],
      reversed: ["Rebellion", "Dogma", "Personal Truth", "Unconventional"],
    },
    summary: {
      upright: "Seek wisdom from proven traditions, trusted mentors, or your deepest foundational values.",
      reversed: "Question inherited dogmas that no longer resonate. Carve your own authentic path of understanding.",
    },
  },
  {
    id: "major-06-the-lovers",
    name: "The Lovers",
    number: 6,
    romanNumeral: "VI",
    arcana: "major",
    suit: null,
    element: "air",
    archetype: "Sacred Union, Moral Choice & Harmony",
    keywords: {
      upright: ["Alignment", "Values", "Partnership", "Choice"],
      reversed: ["Disharmony", "Misalignment", "Inner Conflict", "Compromise"],
    },
    summary: {
      upright: "A moment of deep alignment. Choose what honors your highest integrity and brings harmonious union.",
      reversed: "Address underlying imbalances or conflicting loyalties before making an important life commitment.",
    },
  },
  {
    id: "major-07-the-chariot",
    name: "The Chariot",
    number: 7,
    romanNumeral: "VII",
    arcana: "major",
    suit: null,
    element: "water",
    archetype: "Directed Focus & Tamed Dualities",
    keywords: {
      upright: ["Determination", "Drive", "Focus", "Victory"],
      reversed: ["Lack of Direction", "Aggression", "Loss of Control", "Burnout"],
    },
    summary: {
      upright: "Harness opposing forces with calm determination. Move forward with centered discipline and conviction.",
      reversed: "Pause if you feel out of control or rushing heedlessly. Re-align your direction before pressing the gas.",
    },
  },
  {
    id: "major-08-strength",
    name: "Strength",
    number: 8,
    romanNumeral: "VIII",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Compassionate Courage & Soft Mastery",
    keywords: {
      upright: ["Patience", "Compassion", "Inner Fortitude", "Gentle Power"],
      reversed: ["Self-Doubt", "Raw Emotion", "Weakness", "Impatience"],
    },
    summary: {
      upright: "Mastery through gentle love rather than brute force. Tame the wild impulses within through calm acceptance.",
      reversed: "Quiet the inner critic. You have more resilience than you currently acknowledge.",
    },
  },
  {
    id: "major-09-the-hermit",
    name: "The Hermit",
    number: 9,
    romanNumeral: "IX",
    arcana: "major",
    suit: null,
    element: "earth",
    archetype: "Solitude, Contemplation & The Inner Lantern",
    keywords: {
      upright: ["Introspection", "Solitude", "Soul Searching", "Inner Guidance"],
      reversed: ["Isolation", "Loneliness", "Withdrawal", "Ignoring Truth"],
    },
    summary: {
      upright: "Step away from the crowd. A period of quiet solitude illuminates the truth you have been seeking.",
      reversed: "Distinguish between restorative sacred solitude and unhealthy isolation. Do not fear re-entering the world.",
    },
  },
  {
    id: "major-10-wheel-of-fortune",
    name: "Wheel of Fortune",
    number: 10,
    romanNumeral: "X",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Cycles of Change & Cosmic Timing",
    keywords: {
      upright: ["Cycles", "Destiny", "Turning Point", "Change"],
      reversed: ["Resistance", "Bad Timing", "Disruption", "Clinging"],
    },
    summary: {
      upright: "Life is in fluid motion. Embrace the inevitable turn of the wheel with equanimity and curiosity.",
      reversed: "Resisting natural cycles only creates suffering. Flow with the transition rather than resisting it.",
    },
  },
  {
    id: "major-11-justice",
    name: "Justice",
    number: 11,
    romanNumeral: "XI",
    arcana: "major",
    suit: null,
    element: "air",
    archetype: "Equilibrium, Karma & Unvarnished Truth",
    keywords: {
      upright: ["Truth", "Fairness", "Accountability", "Cause & Effect"],
      reversed: ["Bias", "Avoidance", "Injustice", "Dishonesty"],
    },
    summary: {
      upright: "Examine the situation with clear, objective honesty. Take full accountability for your thoughts and actions.",
      reversed: "Where might you be deceiving yourself or treating others unfairly? Rebalance the scales within.",
    },
  },
  {
    id: "major-12-the-hanged-man",
    name: "The Hanged Man",
    number: 12,
    romanNumeral: "XII",
    arcana: "major",
    suit: null,
    element: "water",
    archetype: "Surrender, New Perspective & Sacred Pause",
    keywords: {
      upright: ["Surrender", "Pause", "New Perspective", "Letting Go"],
      reversed: ["Stalling", "Resistance", "Martyrdom", "Futile Struggle"],
    },
    summary: {
      upright: "Stop trying to force an outcome. Yield, surrender control, and see the situation upside-down.",
      reversed: "Avoid playing the martyr. Distinguish between patient letting go and unnecessary procrastination.",
    },
  },
  {
    id: "major-13-death",
    name: "Death",
    number: 13,
    romanNumeral: "XIII",
    arcana: "major",
    suit: null,
    element: "water",
    archetype: "Profound Metamorphosis & The Pruning Knife",
    keywords: {
      upright: ["Transformation", "Endings", "Transition", "Rebirth"],
      reversed: ["Clinging to the Past", "Fear of Change", "Decay", "Stagnation"],
    },
    summary: {
      upright: "An outdated chapter has concluded. Allow what has died to be released so fertile new life can sprout.",
      reversed: "Clinging to what is already gone prolongs grief. Open your hands and allow the old skin to shed.",
    },
  },
  {
    id: "major-14-temperance",
    name: "Temperance",
    number: 14,
    romanNumeral: "XIV",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Alchemy, Balance & The Middle Path",
    keywords: {
      upright: ["Moderation", "Harmony", "Patience", "Alchemy"],
      reversed: ["Imbalance", "Excess", "Impatience", "Extremes"],
    },
    summary: {
      upright: "Blend the diverse elements of your life into sweet equilibrium. Walk the patient, steady middle path.",
      reversed: "Watch for extremes, emotional reactivity, or overindulgence. Recalibrate your daily rhythm.",
    },
  },
  {
    id: "major-15-the-devil",
    name: "The Devil",
    number: 15,
    romanNumeral: "XV",
    arcana: "major",
    suit: null,
    element: "earth",
    archetype: "The Shadow, Illusions of Bondage & Material Attachments",
    keywords: {
      upright: ["Shadow Self", "Attachment", "Addiction", "Self-Imposed Limits"],
      reversed: ["Liberation", "Awareness", "Breaking Free", "Reclaiming Power"],
    },
    summary: {
      upright: "Examine what unhealthy habits, fears, or attachments hold power over you. The chains are often loose.",
      reversed: "The veil is lifting. You are recognizing a toxic pattern and taking your first steps toward genuine freedom.",
    },
  },
  {
    id: "major-16-the-tower",
    name: "The Tower",
    number: 16,
    romanNumeral: "XVI",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Sudden Revelation & The Shattering of False Illusions",
    keywords: {
      upright: ["Sudden Awakening", "Truth Revelation", "Breakdown", "Liberation"],
      reversed: ["Averting Crisis", "Delayed Truth", "Fear of Disaster", "Clinging"],
    },
    summary: {
      upright: "A lightning strike of truth shatters false foundations. Painful in the moment, but deeply liberating.",
      reversed: "Do not cling to a cracking structure to avoid temporary discomfort. Let the illusion collapse cleanly.",
    },
  },
  {
    id: "major-17-the-star",
    name: "The Star",
    number: 17,
    romanNumeral: "XVII",
    arcana: "major",
    suit: null,
    element: "air",
    archetype: "Spiritual Renewal, Hope & Cosmic Guidance",
    keywords: {
      upright: ["Hope", "Faith", "Healing", "Inspiration"],
      reversed: ["Despair", "Discouragement", "Cynicism", "Disconnection"],
    },
    summary: {
      upright: "After the storm, tranquil peace returns. Trust in the guiding star of your soul; gentle healing is underway.",
      reversed: "Renew your faith in yourself. Do not let temporary exhaustion breed bitter cynicism.",
    },
  },
  {
    id: "major-18-the-moon",
    name: "The Moon",
    number: 18,
    romanNumeral: "XVIII",
    arcana: "major",
    suit: null,
    element: "water",
    archetype: "The Unconscious Realm, Dreams & Mirage",
    keywords: {
      upright: ["Illusion", "Subconscious", "Anxiety", "Intuition"],
      reversed: ["Clarity Emergence", "Conquering Fear", "Truth Revealed", "Unraveling"],
    },
    summary: {
      upright: "Things are not as they appear in the moonlight. Trust your instincts and move slowly through the fog.",
      reversed: "The mist is clearing. Fears that once seemed insurmountable are revealing themselves as paper shadows.",
    },
  },
  {
    id: "major-19-the-sun",
    name: "The Sun",
    number: 19,
    romanNumeral: "XIX",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Vitality, Joy & Illuminating Truth",
    keywords: {
      upright: ["Joy", "Success", "Warmth", "Clarity"],
      reversed: ["Temporary Cloud", "Diminished Joy", "Over-Optimism", "Ego"],
    },
    summary: {
      upright: "Radiant warmth, unbridled vitality, and pure clarity. Celebrate your existence and shine without apology.",
      reversed: "The sun is still shining behind a momentary cloud. Cultivate patience and gratitude for small sparks.",
    },
  },
  {
    id: "major-20-judgement",
    name: "Judgement",
    number: 20,
    romanNumeral: "XX",
    arcana: "major",
    suit: null,
    element: "fire",
    archetype: "Soul Awakening, Reckoning & Higher Calling",
    keywords: {
      upright: ["Awakening", "Reckoning", "Higher Purpose", "Forgiveness"],
      reversed: ["Self-Doubt", "Harsh Self-Criticism", "Hesitation", "Regret"],
    },
    summary: {
      upright: "Hear the clarion call of your higher self. Forgive the past, accept the lessons, and step into renewal.",
      reversed: "Release harsh self-condemnation. You cannot awaken to your next chapter while punishing past mistakes.",
    },
  },
  {
    id: "major-21-the-world",
    name: "The World",
    number: 21,
    romanNumeral: "XXI",
    arcana: "major",
    suit: null,
    element: "earth",
    archetype: "Wholeness, Completion & Integrated Mastery",
    keywords: {
      upright: ["Completion", "Integration", "Accomplishment", "Wholeness"],
      reversed: ["Incomplete Cycles", "Lack of Closure", "Shortcuts", "Delay"],
    },
    summary: {
      upright: "The cycle is complete. You have integrated the lessons and stepped into profound wholeness.",
      reversed: "Tie up loose ends before rushing into the next adventure. Honor the closure of this chapter.",
    },
  },
];

export const SPREADS: SpreadDefinition[] = [
  {
    id: "single-card",
    name: "Daily Archetypal Reflection",
    cardCount: 1,
    description: "A single card drawn for morning mindfulness, grounding, or a focused contemplation on today's theme.",
    positions: [
      {
        id: "daily-focus",
        title: "Daily Focus & Guiding Theme",
        description: "The core archetypal energy available for your reflection today.",
      },
    ],
  },
  {
    id: "three-card-timeline",
    name: "Past, Present & Future Trajectory",
    cardCount: 3,
    description: "A timeless 3-card spread exploring the roots, present realities, and unfolding momentum of your query.",
    positions: [
      {
        id: "past",
        title: "The Foundation (Past)",
        description: "The historical context, underlying root cause, or formative influence.",
      },
      {
        id: "present",
        title: "The Crucible (Present)",
        description: "The current state of energy, immediate challenges, and active influences.",
      },
      {
        id: "future",
        title: "The Trajectory (Future)",
        description: "The natural trajectory unfolding if current attitudes and actions continue.",
      },
    ],
  },
  {
    id: "two-paths",
    name: "The Decisional Crossroads",
    cardCount: 3,
    description: "Clarifies complex crossroads by examining where you stand alongside two potential branches of action.",
    positions: [
      {
        id: "crossroads-anchor",
        title: "Where You Stand",
        description: "Your current inner state and the nature of the tension you face.",
      },
      {
        id: "path-a",
        title: "Path of Continuity / Choice A",
        description: "The energetic outcome and lessons of maintaining course or choosing Option A.",
      },
      {
        id: "path-b",
        title: "Path of Departure / Choice B",
        description: "The energetic outcome and lessons of pivoting toward Option B.",
      },
    ],
  },
];
